countries_data = [
    "US", "JP", "IT", "KR", "FR", "DE", "TW", "RU", "GB", "NL",
    "CZ", "TR", "AT", "CH", "ES", "CA", "SE", "IL", "PL", "IR",
    "NO", "RO", "IN", "VN", "BE", "BR", "BG", "ID", "DK", "AR",
    "MX", "FI", "CN", "CL", "ZA", "SK", "HU", "IE", "EG", "TH",
    "UA", "RS", "HK", "GR", "PT", "LV", "SG", "IS", "MY", "CO",
    "TN", "EE", "DO", "SI", "EC", "LT", "PS", "NZ", "BD", "PA",
    "MD", "NI", "MT", "TT", "SA", "HR", "CY", "PK", "AE", "KZ",
    "KW", "VE", "GE", "ME", "SV", "LU", "CW", "PR", "CR", "BY",
    "AL", "LI", "BA", "PY", "PH", "FO", "GT", "NP", "PE", "UY",
    "-" , "AD", "AG", "AM", "AO", "AU", "AW", "AZ", "BB", 
    "BQ", "BS", "BW", "CG", "CI", "DZ", "FJ", "GA", "GG", "GL",
    "GP", "GU", "GY", "HN", "JE", "JM", "JO", "KE", "KH", "KN",
    "KY", "LA", "LB", "LK", "MA", "MG", "MK", "MN", "MO", "MQ",
    "MU", "NA", "NC", "NG", "QA", "RE", "SD", "SN", "SR", "ST",
    "SY", "TZ", "UG", "UZ", "VC","BJ", 
]